<<<<<<< HEAD
dEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : 'ue5'          # output folder name used for saving the model, logs and inference results

MODEL:
  NAME          : MixTransformer                                            # name of the model you are using
  BACKBONE      : 'B4'                          # model variant
  PRETRAINED    : '/nvme/SISLab/MIT_checkpts/'     # backbone model's weight
  RESUME        : ''                                                # checkpoint file

DATASET:
  NAME          : UE5                                          # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/nvme/SISLab/Datasets/UE5_Dataset_V1'                # dataset root path
  IGNORE_LABEL  : 255
  MODALS        : ['image']
  #MODALS        : ['image', 'depth']

TRAIN:
  IMAGE_SIZE    : [512, 512]      # training image size in (h, w)
  BATCH_SIZE    : 8               # batch size used to train
  EPOCHS        : 200             # number of epochs to train
  EVAL_START    : 0             # evaluation interval during training
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : true           # use AMP in training
  DDP           : false            # use DDP training

LOSS:
  NAME          : CrossEntropy     # loss function name
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.00006         # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer 

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  # MODEL_PATH    : 'output/MCubeS/cmnext_b2_mcubes_rgb.pth'
  # MODEL_PATH    : 'output/MCubeS/cmnext_b2_mcubes_rgba.pth'
  # MODEL_PATH    : 'output/MCubeS/cmnext_b2_mcubes_rgbad.pth'
  MODEL_PATH    : 'ue5/UE5_3_id/20250312-154410/UNet_3_UE5_epoch192_62.01_checkpoint.pth'
  IMAGE_SIZE    : [1024, 1024]    # evaluation image size in (h, w)
  BATCH_SIZE    : 1               # batch size used to train
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                
=======
DATASET:
  IGNORE_LABEL: 255
  MODALS:
  - image
  NAME: UE5
  ROOT: /home/justin/PycharmProjects/Datasets/UE5_Dataset_V1
DEVICE: cuda
EVAL:
  BATCH_SIZE: 1
  IMAGE_SIZE:
  - 1024
  - 1792
  MODEL_PATH: results/ue5/20250820-151353/best_model_epoch291_mIoU74.9800.pth
  MSF:
    ENABLE: false
    FLIP: true
    SCALES:
    - 0.5
    - 0.75
    - 1.0
    - 1.25
    - 1.5
    - 1.75
LOSS:
  CLS_WEIGHTS: false
  NAME: CrossEntropy
MODEL:
  BACKBONE: CMX-B4
  NAME: CMX
  PRETRAINED: /home/justin/PycharmProjects/Checkpoints/mit_b4.pth
  RESUME: ''
OPTIMIZER:
  LR: 6.0e-05
  NAME: AdamW
  WEIGHT_DECAY: 0.01
SAVE_DIR: results/ue5
SCHEDULER:
  NAME: WarmupPolyLR
  POWER: 0.9
  WARMUP: 10
  WARMUP_RATIO: 0.1
TRAIN:
  AMP: true
  BATCH_SIZE: 2
  DDP: true
  EPOCHS: 300
  EVAL_INTERVAL: 1
  EVAL_START: 0
  IMAGE_SIZE:
  - 768
  - 1280
>>>>>>> e721620 (update yaml for cmx)
